from typing import Any, Iterator, Literal

import pyarrow

__version__: str
Frame = Literal["arrow", "polars", "pandas"]

class Partition:
    venue: str
    symbol: str
    date: str
    book_level: int
    rows: int
    files: int
    bytes: int
    first_ns: int
    last_ns: int
    @property
    def seconds(self) -> float: ...

class Book:
    @property
    def bids(self) -> list[tuple[float, float]]: ...
    @property
    def asks(self) -> list[tuple[float, float]]: ...
    @property
    def best_bid(self) -> tuple[float, float] | None: ...
    @property
    def best_ask(self) -> tuple[float, float] | None: ...
    @property
    def mid(self) -> float | None: ...
    @property
    def spread(self) -> float | None: ...
    @property
    def spread_bps(self) -> float | None: ...
    @property
    def depth(self) -> tuple[int, int]: ...
    @property
    def digest(self) -> int: ...
    @property
    def suspect(self) -> bool: ...
    @property
    def suspect_rows(self) -> int: ...
    @property
    def origin(self) -> str: ...
    @property
    def rows_applied(self) -> int: ...
    @property
    def at_ns(self) -> int: ...
    def imbalance(self, depth: int = 10) -> float | None: ...
    def depth_within(self, offset: float) -> tuple[float, float] | None: ...
    def to_arrow(self) -> pyarrow.RecordBatch: ...

class Tick:
    at_ns: int
    venue_ts_ns: int | None
    bid: float | None
    ask: float | None
    mid: float | None
    spread: float | None
    changes: int
    suspect: bool
    traded_qty: float | None

class Replay:
    def __iter__(self) -> Replay: ...
    def __next__(self) -> Tick: ...
    @property
    def book(self) -> Book: ...
    @property
    def delivered(self) -> int: ...
    @property
    def files_opened(self) -> int: ...

class Archive:
    def __init__(self, path: Any) -> None: ...
    @property
    def path(self) -> str: ...
    def partitions(self) -> list[Partition]: ...
    def symbols(self) -> list[tuple[str, str]]: ...
    def span_ns(self, venue: str, symbol: str) -> tuple[int, int]: ...
    def verify(self) -> dict[str, Any]: ...
    def book_at(
        self, venue: str, symbol: str, at: str | int, depth: int | None = ...
    ) -> Book: ...
    def bars(
        self,
        venue: str,
        symbol: str,
        bar_seconds: float = ...,
        start: str | int | None = ...,
        end: str | int | None = ...,
        depth: int = ...,
        frame: Frame = ...,
    ) -> Any: ...
    def replay(
        self,
        venue: str,
        symbol: str,
        speed: float = ...,
        start: str | int | None = ...,
        end: str | int | None = ...,
        depth: int | None = ...,
    ) -> Replay: ...
    def ticks(self, venue: str, symbol: str, **kwargs: Any) -> Iterator[Tick]: ...
    def plot_book(
        self,
        venue: str,
        symbol: str,
        at: str | int,
        depth: int = ...,
        ax: Any = ...,
        show: bool = ...,
    ) -> Any: ...

def isoformat(at_ns: int) -> str:
    """Render a nanosecond instant as RFC 3339, keeping all nine digits."""
    ...

def open(path: Any) -> Archive: ...
def venues() -> list[str]: ...
def capabilities() -> list[dict[str, Any]]: ...
def to_polars(batch: pyarrow.RecordBatch) -> Any: ...
def to_pandas(batch: pyarrow.RecordBatch) -> Any: ...
